.PHONY: async
async:
	rsync -av ~/workspace/core/report-sdk/libs/ root@47.242.177.227:~/workspace/changecoder/ccui/public/scripts/
	rsync -av ~/workspace/website/index.html root@47.242.177.227:~/workspace/changecoder/ccui/